// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login-signup": {
    params: {};
  };
  "/create-profile": {
    params: {};
  };
  "/connect": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/user": {
    params: {};
  };
  "/messages": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login-signup" | "/create-profile" | "/connect" | "/profile" | "/user" | "/messages";
  };
  "routes/login-signup.tsx": {
    id: "routes/login-signup";
    page: "/login-signup";
  };
  "routes/create-profile.tsx": {
    id: "routes/create-profile";
    page: "/create-profile";
  };
  "layouts/navigation.tsx": {
    id: "layouts/navigation";
    page: "/" | "/connect" | "/profile" | "/user" | "/messages";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/matching-profiles.tsx": {
    id: "routes/matching-profiles";
    page: "/connect";
  };
  "routes/my-profile.tsx": {
    id: "routes/my-profile";
    page: "/profile";
  };
  "routes/user-profile-page.tsx": {
    id: "routes/user-profile-page";
    page: "/user";
  };
  "routes/view-connections-messages.tsx": {
    id: "routes/view-connections-messages";
    page: "/messages";
  };
};