// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/connect": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/connect";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/matching-profiles.tsx": {
    id: "routes/matching-profiles";
    page: "/connect";
  };
};