// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/create-profile": {
    params: {};
  };
  "/api/post-user-interests": {
    params: {};
  };
  "/api/delete-user-interests": {
    params: {};
  };
  "/signout": {
    params: {};
  };
  "/activate/:userActivationToken?": {
    params: {
      "userActivationToken"?: string;
    };
  };
  "/connect/:interestId?": {
    params: {
      "interestId"?: string;
    };
  };
  "/profile": {
    params: {};
  };
  "/user/:partnerId?": {
    params: {
      "partnerId"?: string;
    };
  };
  "/chat/:partnerId?": {
    params: {
      "partnerId"?: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/create-profile" | "/api/post-user-interests" | "/api/delete-user-interests" | "/signout" | "/activate/:userActivationToken?" | "/connect/:interestId?" | "/profile" | "/user/:partnerId?" | "/chat/:partnerId?";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/create-profile.tsx": {
    id: "routes/create-profile";
    page: "/create-profile";
  };
  "routes/interest-component-route.tsx": {
    id: "routes/interest-component-route";
    page: "/api/post-user-interests";
  };
  "routes/delete-interest-route.tsx": {
    id: "routes/delete-interest-route";
    page: "/api/delete-user-interests";
  };
  "routes/signout.tsx": {
    id: "routes/signout";
    page: "/signout";
  };
  "routes/activation.tsx": {
    id: "routes/activation";
    page: "/activate/:userActivationToken?";
  };
  "layouts/navigation.tsx": {
    id: "layouts/navigation";
    page: "/" | "/connect/:interestId?" | "/profile" | "/user/:partnerId?" | "/chat/:partnerId?";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/matching-profiles.tsx": {
    id: "routes/matching-profiles";
    page: "/connect/:interestId?";
  };
  "routes/my-profile.tsx": {
    id: "routes/my-profile";
    page: "/profile";
  };
  "routes/user-profile-page.tsx": {
    id: "routes/user-profile-page";
    page: "/user/:partnerId?";
  };
  "layouts/messaging.tsx": {
    id: "layouts/messaging";
    page: "/chat/:partnerId?";
  };
  "routes/main-chat.tsx": {
    id: "routes/main-chat";
    page: "/chat/:partnerId?";
  };
};